print('========================')
print('Ola, Mundo!')
print('====== DESAFIO 01 ======')
nome=input('Qual o seu nome? ')
idade=input('Qual a sua idade? ')
peso=input('Qual o seu peso? ')
print('========================')
print(nome, idade, peso)
print('========================')