print('=============== CADASTRO ===============')
nome=input('Qual é o seu primeiro nome? ')
sob=input('Qual o sobrenome? ')
idade=input('Qual sua idade? ')
dia=input('Qual o dia do seu nascimento? ')
mes=input('Qual o mês do seu nascimento? ')
ano=input('Qual o ano do seu nascimento? ')
alt=input('Qual a sua altura? ')
peso=input('Qual o seu peso? ')
cpf=input('Qual o seu CPF? ')
rg=input('Qual o seu RG? ')
pais=input('Qual o país onde vive? ')
uf=input('Qual a unidade federativa? ')
cid=input('Qual a cidade onde mora? ')
bairro=input('Qual o bairro? ')
cep=input('Qual o CEP? ')
end=input('Qual o nome da rua? ')
num=input('Qual o número da residência? ')
comp=input('Qual o complemento? ')

print('=========================================')
print('============== INFORMAÇÕES ==============')
print('Nome:',nome,'',sob)
print('Idade: ',idade)
print('Data de nascimento: {}/{}/{}'.format(dia,mes,ano))
print('Sua altura é',alt,'m')
print('Seu peso é',peso,'k')
print('-----------Dados importantes:------------')
print('CPF:',cpf)
print('RG:',rg)
print('----------------Endereço:----------------')
print('País: {} / UF: {} / Cidade: {}'.format(pais,uf,cid))
print('CEP:',cep)
print('Bairro:',bairro)
print('Rua: {}, {}, {}'.format(end,num,comp))
print('=========================================')
print('=========================================')